# Site settings
title: ksgbabu.com
email: me@ksgbabu.com, giri4it@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  writing on what we work is fun and when that mix with the life that becomes hilarious.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: giri4it
github_username:  giri4it

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num"
collection:
	- services
	